export const getShowdownName = (name: string, isFemale: boolean = false) => {
  if (!name) return '';
  let slug = name.toLowerCase().trim();
  
  // Mega/Gmax/Form/Paradox handling
  const specialForms: Record<string, string> = {
    'ho-oh': 'hooh',
    'kommo-o': 'kommoo',
    'hakamo-o': 'hakamoo',
    'jangmo-o': 'jangmoo',
    'porygon-z': 'porygonz',
    'sirfetchd': 'sirfetchd',
    'farfetchd': 'farfetchd',
    'mr-mime': 'mrmime',
    'mr-rime': 'mrrime',
    'mime-jr': 'mimejr',
    'type-null': 'typenull',
    'wo-chien': 'wochien',
    'chien-pao': 'chienpao',
    'ting-lu': 'tinglu',
    'chi-yu': 'chiyu',
    'great-tusk': 'greattusk',
    'scream-tail': 'screamtail',
    'brute-bonnet': 'brutebonnet',
    'flutter-mane': 'fluttermane',
    'slither-wing': 'slitherwing',
    'sandy-shocks': 'sandyshocks',
    'iron-treads': 'irontreads',
    'iron-bundle': 'ironbundle',
    'iron-hands': 'ironhands',
    'iron-jugulis': 'ironjugulis',
    'iron-moth': 'ironmoth',
    'iron-thorns': 'ironthorns',
    'iron-valiant': 'ironvaliant',
    'iron-leaves': 'ironleaves',
    'walking-wake': 'walkingwake',
    'iron-boulder': 'ironboulder',
    'iron-crown': 'ironcrown',
    'raging-bolt': 'ragingbolt',
    'gouging-fire': 'gougingfire',
    'flabebe': 'flabebe',
    'meowscarada': 'meowscarada',
    'skeledirge': 'skeledirge',
    'quaquaval': 'quaquaval',
    'oricorio-baile': 'oricorio',
    'oricorio-pom-pom': 'oricorio-pompom',
    'oricorio-pa-u': 'oricorio-pau',
    'oricorio-sensu': 'oricorio-sensu',
    'lycanroc-midday': 'lycanroc',
    'lycanroc-midnight': 'lycanroc-midnight',
    'lycanroc-dusk': 'lycanroc-dusk',
    'minior-red-meteor': 'minior',
    'minior-red': 'minior',
    'minior-orange-meteor': 'minior',
    'minior-orange': 'minior-orange',
    'minior-yellow-meteor': 'minior',
    'minior-yellow': 'minior-yellow',
    'minior-green-meteor': 'minior',
    'minior-green': 'minior-green',
    'minior-blue-meteor': 'minior',
    'minior-blue': 'minior-blue',
    'minior-indigo-meteor': 'minior',
    'minior-indigo': 'minior-indigo',
    'minior-violet-meteor': 'minior',
    'minior-violet': 'minior-violet',
    'mimikyu-disguised': 'mimikyu',
    'mimikyu-busted': 'mimikyu-busted',
    'zygarde-10': 'zygarde10',
    'zygarde-50': 'zygarde',
    'basculin-red-striped': 'basculin',
    'basculin-blue-striped': 'basculin-blue',
    'basculin-white-striped': 'basculin-white',
    'keldeo-ordinary': 'keldeo',
    'keldeo-resolute': 'keldeo-resolute',
    'meloetta-aria': 'meloetta',
    'meloetta-pirouette': 'meloetta-pirouette',
    'thundurus-incarnate': 'thundurus',
    'thundurus-therian': 'thundurus-therian',
    'tornadus-incarnate': 'tornadus',
    'tornadus-therian': 'tornadus-therian',
    'landorus-incarnate': 'landorus',
    'landorus-therian': 'landorus-therian',
    'enamorus-incarnate': 'enamorus',
    'enamorus-therian': 'enamorus-therian',
    'gourgeist-average': 'gourgeist',
    'gourgeist-small': 'gourgeist-small',
    'gourgeist-large': 'gourgeist-large',
    'gourgeist-super': 'gourgeist-super',
    'pumpkaboo-average': 'pumpkaboo',
    'pumpkaboo-small': 'pumpkaboo-small',
    'pumpkaboo-large': 'pumpkaboo-large',
    'pumpkaboo-super': 'pumpkaboo-super',
    'toxtricity-amped': 'toxtricity',
    'toxtricity-low-key': 'toxtricity-lowkey',
    'urshifu-single-strike': 'urshifu',
    'urshifu-rapid-strike': 'urshifu-rapidstrike',
    'deoxys-normal': 'deoxys',
    'deoxys-attack': 'deoxys-attack',
    'deoxys-defense': 'deoxys-defense',
    'deoxys-speed': 'deoxys-speed',
    'wormadam-plant': 'wormadam',
    'wormadam-sandy': 'wormadam-sandy',
    'wormadam-trash': 'wormadam-trash',
    'giratina-altered': 'giratina',
    'giratina-origin': 'giratina-origin',
    'shaymin-land': 'shaymin',
    'shaymin-sky': 'shaymin-sky',
    'aegislash-shield': 'aegislash',
    'aegislash-blade': 'aegislash-blade',
    'basculegion-male': 'basculegion',
    'basculegion-female': 'basculegion-f',
    'meowstic-male': 'meowstic',
    'meowstic-female': 'meowstic-f',
    'indeedee-male': 'indeedee',
    'indeedee-female': 'indeedee-f',
    'oinkologne-male': 'oinkologne',
    'oinkologne-female': 'oinkologne-f',
    'pyroar-male': 'pyroar',
    'pyroar-female': 'pyroar-f',
    'unfezant-male': 'unfezant',
    'unfezant-female': 'unfezant-f',
    'frillish-male': 'frillish',
    'frillish-female': 'frillish-f',
    'jellicent-male': 'jellicent',
    'jellicent-female': 'jellicent-f',
    'meowstic': 'meowstic',
    'indeedee': 'indeedee',
    'oinkologne': 'oinkologne',
    'pyroar': 'pyroar',
    'unfezant': 'unfezant',
    'frillish': 'frillish',
    'jellicent': 'jellicent',
    'hippowdon': 'hippowdon',
    'hippopotas': 'hippopotas',
    'basculegion': 'basculegion',
    'nidoran-m': 'nidoranm',
    'nidoran-f': 'nidoranf',
    'hippowdon-male': 'hippowdon',
    'hippowdon-female': 'hippowdon-f',
    'hippopotas-male': 'hippopotas',
    'hippopotas-female': 'hippopotas-f',
    'darmanitan-standard': 'darmanitan',
    'darmanitan-zen': 'darmanitan-zen',
    'darmanitan-galar-standard': 'darmanitan-galar',
    'darmanitan-galar-zen': 'darmanitan-galar-zen',
    'wishiwashi-solo': 'wishiwashi',
    'wishiwashi-school': 'wishiwashi-school',
    'zygarde-10-power-construct': 'zygarde10',
    'zygarde-50-power-construct': 'zygarde',
    'zygarde-complete': 'zygarde-complete',
    'greninja-ash': 'greninja-ash',
    'necrozma-dusk': 'necrozma-duskmane',
    'necrozma-dawn': 'necrozma-dawnwings',
    'necrozma-ultra': 'necrozma-ultra',
    'calyrex-ice': 'calyrex-ice',
    'calyrex-shadow': 'calyrex-shadow',
    'palafin-zero': 'palafin',
    'palafin-hero': 'palafin-hero',
    'maushold-family-of-three': 'maushold',
    'maushold-family-of-four': 'maushold',
    'dudunsparce-two-segment': 'dudunsparce',
    'dudunsparce-three-segment': 'dudunsparce-threesegment',
    'ogerpon-teal-mask': 'ogerpon',
    'ogerpon-wellspring-mask': 'ogerpon-wellspring',
    'ogerpon-hearthflame-mask': 'ogerpon-hearthflame',
    'ogerpon-cornerstone-mask': 'ogerpon-cornerstone',
    'terapagos-normal': 'terapagos',
    'terapagos-terastal': 'terapagos-terastal',
    'terapagos-stellar': 'terapagos-stellar',
  };

  if (specialForms[slug] || slug === 'pyroar' || slug === 'meowstic') {
    let result = specialForms[slug] || slug;
    if (isFemale && !result.endsWith('f')) {
      const dashFemale = ['meowstic', 'indeedee', 'basculegion', 'oinkologne', 'pyroar', 'unfezant', 'frillish', 'jellicent', 'hippowdon', 'hippopotas'];
      if (dashFemale.includes(result)) {
        result += '-f';
      } else {
        result += 'f';
      }
    }
    return result;
  }

  // Default stripping logic for species that doesn't have a special form mapping
  let processed = slug.toLowerCase().replace(/[^a-z0-9]/g, '');
  
  if (isFemale) {
    if (processed === 'nidoranm') return 'nidoranf';
    if (!processed.endsWith('f')) {
      processed += 'f'; // Showdown uses pikachuf, wobbuffetf, etc without dash
    }
  }

  return processed;
};
